export const HOME_PAGE = '/'
export const NEWIN_PAGE = '/newin'
export const PRODUCT_PAGE = '/product'
export const CATEGORY_PAGE = '/category'
export const CONTACT_PAGE = '/contact'

export const PROFILE_PAGE = '/profile'
export const LOGIN_PAGE = '/login'
export const REGISTER_PAGE = '/register'
export const CART_PAGE = '/cart'
export const ORDER_PAGE = '/order'
export const AUTH_SUCCESS = 'auth/success'
